version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - networks

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: the-moment-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - networks

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: the-moment-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - networks
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./roles.yml:/roles.yml
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
      SPRING_CONFIG_ADDITIONAL-LOCATION: /roles.yml
    networks:
      - networks

networks:
  networks:
